# Generated by Django 6.0 on 2026-08-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_alter_episode_options'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='episode',
            index=models.Index(fields=['air_date'], name='media_episo_air_dat_0a1b60_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['release_date'], name='media_movie_release_61672d_idx'),
        ),
    ]
