# Generated by Django 6.1 on 2026-08-17 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_episode_media_episo_air_dat_0a1b60_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='EpisodeCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cast', models.JSONField(blank=True, default=list)),
                ('crew', models.JSONField(blank=True, default=list)),
                ('guest_stars', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('episode', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='media.episode')),
            ],
        ),
    ]
