# Generated by Django 6.1 on 2026-09-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0006_episode_episode_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='broadcast_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='external_ids',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='season',
            name='external_ids',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='tvshow',
            name='external_ids',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
