# Generated by Django 6.1 on 2026-09-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0009_episode_next_episode'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='vote_average',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='season',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
    ]
