# Generated by Django 6.1 on 2026-09-28 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0010_season_vote_average_season_vote_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='has_postcredits_scene',
            field=models.BooleanField(default=False),
        ),
    ]
