import { createRouter, createWebHistory, type RouteRecordRaw } from 'vue-router'
import { useAuthStore } from '@/stores/auth'

const authMeta = { requiresAuth: true }
const routes: RouteRecordRaw[] = [
  { path: '/', component: () => import('@/views/HomeView.vue'), name: 'home', meta: { guest: true } }, { path: '/dashboard', component: () => import('@/views/DashboardView.vue'), name: 'dashboard', meta: authMeta }, { path: '/my-shows', component: () => import('@/views/MyShowsView.vue'), name: 'my-shows', meta: authMeta }, { path: '/my-movies', component: () => import('@/views/MyMoviesView.vue'), name: 'my-movies', meta: authMeta }, { path: '/login', component: () => import('@/views/LoginView.vue'), name: 'login', meta: { guest: true } }, { path: '/register', component: () => import('@/views/RegisterView.vue'), name: 'register', meta: { guest: true } }, { path: '/search', component: () => import('@/views/SearchView.vue'), name: 'search', meta: authMeta }, { path: '/movies/:id', component: () => import('@/views/MovieDetailView.vue'), name: 'movie-detail', meta: authMeta }, { path: '/tv/:id', component: () => import('@/views/TVDetailView.vue'), name: 'tv-detail', meta: authMeta }, { path: '/tv/:id/season/:seasonNumber', component: () => import('@/views/SeasonDetailView.vue'), name: 'season-detail', meta: authMeta }, { path: '/tv/:id/season/:seasonNumber/episode/:episodeNumber', component: () => import('@/views/EpisodeDetailView.vue'), name: 'episode-detail', meta: authMeta }, { path: '/watchlist', component: () => import('@/views/WatchlistView.vue'), name: 'watchlist', meta: authMeta }, { path: '/history', component: () => import('@/views/HistoryView.vue'), name: 'history', meta: authMeta }, { path: '/profile/:username', component: () => import('@/views/ProfileView.vue'), name: 'profile', meta: authMeta }, { path: '/profile/:username/followers', component: () => import('@/views/ProfileFollowersView.vue'), name: 'profile-followers', meta: authMeta }, { path: '/profile/:username/following', component: () => import('@/views/ProfileFollowingView.vue'), name: 'profile-following', meta: authMeta }, { path: '/settings', component: () => import('@/views/SettingsView.vue'), name: 'settings', meta: authMeta }, { path: '/calendar', component: () => import('@/views/CalendarView.vue'), name: 'calendar', meta: authMeta }, { path: '/data', component: () => import('@/views/DataTransferView.vue'), name: 'data-transfer', meta: authMeta }, { path: '/lists', component: () => import('@/views/ListsView.vue'), name: 'lists', meta: authMeta }, { path: '/lists/:id', component: () => import('@/views/ListDetailView.vue'), name: 'list-detail', meta: authMeta },
]
const router = createRouter({ history: createWebHistory(), routes, scrollBehavior: () => ({ top: 0 }) })
router.beforeEach(async (to) => { const auth = useAuthStore(); if (to.meta.requiresAuth && !auth.isAuthenticated) { if (localStorage.getItem('access_token') && !auth.user) await auth.init(); if (!auth.isAuthenticated) return { name: 'login', query: { redirect: to.fullPath } } } if (to.meta.guest && auth.isAuthenticated) return { name: 'dashboard' } })
export default router
