# Generated by Django 6.0 on 2026-05-06 11:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_customlist_listitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='watchentry',
            constraint=models.UniqueConstraint(fields=('user', 'media_type', 'tmdb_id'), name='unique_user_media_tmdb'),
        ),
    ]
