# Generated by Django 6.0 on 2026-05-06 11:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_add_unique_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='watchentry',
            name='unique_user_media_tmdb',
        ),
        migrations.AlterField(
            model_name='watchentry',
            name='media_type',
            field=models.CharField(choices=[('movie', 'Movie'), ('episode', 'Episode')], max_length=10),
        ),
        migrations.AddIndex(
            model_name='watchentry',
            index=models.Index(fields=['user', 'media_type', 'tmdb_id', 'season_number', 'episode_number'], name='tracking_wa_user_id_c2bec8_idx'),
        ),
        migrations.AddConstraint(
            model_name='watchentry',
            constraint=models.UniqueConstraint(condition=models.Q(('media_type', 'movie')), fields=('user', 'media_type', 'tmdb_id'), name='unique_user_movie_tmdb'),
        ),
        migrations.RemoveField(
            model_name='watchentry',
            name='progress_episode',
        ),
        migrations.RemoveField(
            model_name='watchentry',
            name='progress_season',
        ),
    ]
