# Generated by Django 6.0 on 2026-08-03 20:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0010_alter_datatransferjob_data_format'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='datatransferjob',
            index=models.Index(fields=['user', 'created_at'], name='tracking_da_user_id_e12621_idx'),
        ),
        migrations.AddIndex(
            model_name='datatransferjob',
            index=models.Index(fields=['user', 'status', 'created_at'], name='tracking_da_user_id_339266_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['user', 'updated_at'], name='tracking_ra_user_id_2f3dea_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['media_type', 'tmdb_id', 'created_at'], name='tracking_re_media_t_37ee56_idx'),
        ),
        migrations.AddIndex(
            model_name='watchentry',
            index=models.Index(fields=['user', 'status', 'media_type', 'watched_at'], name='tracking_wa_user_id_fc718d_idx'),
        ),
        migrations.AddIndex(
            model_name='watchentry',
            index=models.Index(fields=['user', 'media_type', 'status', 'tmdb_id'], name='tracking_wa_user_id_863851_idx'),
        ),
        migrations.AddIndex(
            model_name='watchlist',
            index=models.Index(fields=['user', 'added_at'], name='tracking_wa_user_id_ce6290_idx'),
        ),
    ]
