# Generated by Django 6.0 on 2026-08-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0011_datatransferjob_tracking_da_user_id_e12621_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatransferjob',
            name='source',
            field=models.CharField(choices=[('local', 'Local file')], default='local', max_length=20),
        ),
        migrations.DeleteModel(
            name='TraktImportSchedule',
        ),
    ]
