# Generated by Django 6.0 on 2026-08-05 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0012_alter_datatransferjob_source_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSeasonStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField()),
                ('season_number', models.IntegerField()),
                ('status', models.CharField(choices=[('none', 'None'), ('watching', 'Watching'), ('watched', 'Watched')], default='none', max_length=20)),
                ('watched_episodes', models.IntegerField(default=0)),
                ('total_episodes', models.IntegerField(default=0)),
                ('progress_percent', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_watched_at', models.DateTimeField(blank=True, null=True)),
                ('status_changed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'status'], name='tracking_us_user_id_41a199_idx'), models.Index(fields=['user', 'tmdb_id'], name='tracking_us_user_id_5c9545_idx'), models.Index(fields=['user', 'updated_at'], name='tracking_us_user_id_1e68e2_idx')],
                'unique_together': {('user', 'tmdb_id', 'season_number')},
            },
        ),
        migrations.CreateModel(
            name='UserTvShowStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField()),
                ('status', models.CharField(choices=[('none', 'None'), ('plan_to_watch', 'Plan to Watch'), ('watching', 'Watching'), ('watched', 'Watched'), ('dropped', 'Dropped')], default='none', max_length=20)),
                ('watched_episodes', models.IntegerField(default=0)),
                ('total_episodes', models.IntegerField(default=0)),
                ('progress_percent', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('dropped_at', models.DateTimeField(blank=True, null=True)),
                ('plan_to_watch_at', models.DateTimeField(blank=True, null=True)),
                ('last_watched_at', models.DateTimeField(blank=True, null=True)),
                ('status_changed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tv_show_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'status'], name='tracking_us_user_id_c13f2d_idx'), models.Index(fields=['user', 'updated_at'], name='tracking_us_user_id_f95bb2_idx')],
                'unique_together': {('user', 'tmdb_id')},
            },
        ),
    ]
