# Generated by Django 6.0 on 2026-08-07 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0013_userseasonstatus_usertvshowstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatransferjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('awaiting_confirmation', 'Awaiting confirmation'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=32),
        ),
    ]
