# Generated by Django 6.0 on 2026-08-17 15:35

from django.db import migrations, models


def followers_to_public(apps, schema_editor):
    CustomList = apps.get_model('tracking', 'CustomList')
    CustomList.objects.filter(privacy='followers').update(privacy='public')


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0014_alter_datatransferjob_status'),
    ]

    operations = [
        migrations.RunPython(followers_to_public, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='customlist',
            name='privacy',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=20),
        ),
    ]
