# Generated by Django 6.1 on 2026-08-20 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_to_usermediastatus(apps, schema_editor):
    UserMediaStatus = apps.get_model('tracking', 'UserMediaStatus')
    UserTvShowStatus = apps.get_model('tracking', 'UserTvShowStatus')
    Watchlist = apps.get_model('tracking', 'Watchlist')

    concrete_statuses = {'watching', 'watched', 'dropped'}

    for item in UserTvShowStatus.objects.all().iterator():
        if item.status == 'none':
            continue

        UserMediaStatus.objects.create(
            user_id=item.user_id,
            media_type='tv',
            tmdb_id=item.tmdb_id,
            status=item.status,
            watched_episodes=item.watched_episodes,
            total_episodes=item.total_episodes,
            progress_percent=item.progress_percent,
            started_at=item.started_at,
            completed_at=item.completed_at,
            dropped_at=item.dropped_at,
            plan_to_watch_at=item.plan_to_watch_at,
            last_watched_at=item.last_watched_at,
            status_changed_at=item.status_changed_at,
            created_at=item.created_at,
            updated_at=item.updated_at,
        )

    for item in Watchlist.objects.all().iterator():
        existing = UserMediaStatus.objects.filter(
            user_id=item.user_id,
            media_type=item.media_type,
            tmdb_id=item.tmdb_id,
        ).values('id', 'status', 'status_changed_at', 'plan_to_watch_at').first()

        if existing is None:
            UserMediaStatus.objects.create(
                user_id=item.user_id,
                media_type=item.media_type,
                tmdb_id=item.tmdb_id,
                status='plan_to_watch',
                plan_to_watch_at=item.added_at,
                status_changed_at=item.added_at,
            )
            continue

        if existing['status'] not in concrete_statuses:
            updates = {'status': 'plan_to_watch'}
            if existing['plan_to_watch_at'] is None and item.added_at is not None:
                updates['plan_to_watch_at'] = item.added_at
            if existing['status_changed_at'] is None and item.added_at is not None:
                updates['status_changed_at'] = item.added_at
            UserMediaStatus.objects.filter(id=existing['id']).update(**updates)


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0020_remove_userseasonstatus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMediaStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('movie', 'Movie'), ('tv', 'TV Show')], max_length=10)),
                ('tmdb_id', models.IntegerField()),
                ('status', models.CharField(choices=[('plan_to_watch', 'Plan to Watch'), ('watching', 'Watching'), ('watched', 'Watched'), ('dropped', 'Dropped')], max_length=20)),
                ('watched_episodes', models.IntegerField(default=0)),
                ('total_episodes', models.IntegerField(default=0)),
                ('progress_percent', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('dropped_at', models.DateTimeField(blank=True, null=True)),
                ('plan_to_watch_at', models.DateTimeField(blank=True, null=True)),
                ('last_watched_at', models.DateTimeField(blank=True, null=True)),
                ('status_changed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='usertvshowstatus',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='usertvshowstatus',
            name='tracking_us_user_id_c13f2d_idx',
        ),
        migrations.RemoveIndex(
            model_name='usertvshowstatus',
            name='tracking_us_user_id_f95bb2_idx',
        ),
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='watchlist',
            name='tracking_wa_user_id_ce6290_idx',
        ),
        migrations.AddField(
            model_name='usermediastatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_statuses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(migrate_to_usermediastatus, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='usertvshowstatus',
            name='user',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='user',
        ),
        migrations.AddIndex(
            model_name='usermediastatus',
            index=models.Index(fields=['user', 'media_type', 'status'], name='tracking_us_user_id_d3bf40_idx'),
        ),
        migrations.AddIndex(
            model_name='usermediastatus',
            index=models.Index(fields=['user', 'updated_at'], name='tracking_us_user_id_7de99b_idx'),
        ),
        migrations.AddConstraint(
            model_name='usermediastatus',
            constraint=models.UniqueConstraint(fields=('user', 'media_type', 'tmdb_id'), name='uniq_user_media_status_entry'),
        ),
        migrations.AddConstraint(
            model_name='usermediastatus',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('media_type', 'movie'), ('status__in', ['plan_to_watch', 'watched', 'dropped'])), models.Q(('media_type', 'tv'), ('status__in', ['plan_to_watch', 'watching', 'watched', 'dropped'])), _connector='OR'), name='media_status_status_matches_media_type'),
        ),
        migrations.DeleteModel(
            name='UserTvShowStatus',
        ),
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
