# Generated by Django 6.1 on 2026-08-26 17:39

from django.db import migrations, models


def backfill_custom_order(apps, schema_editor):
    CustomList = apps.get_model('tracking', 'CustomList')
    ListItem = apps.get_model('tracking', 'ListItem')
    for lst in CustomList.objects.all().iterator():
        items = ListItem.objects.filter(custom_list_id=lst.id).order_by('added_at', 'id')
        for idx, item in enumerate(items):
            ListItem.objects.filter(id=item.id).update(custom_order=idx)


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0021_usermediastatus_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listitem',
            options={'ordering': ['custom_order', 'added_at']},
        ),
        migrations.AddField(
            model_name='listitem',
            name='custom_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name='listitem',
            index=models.Index(fields=['custom_list', 'custom_order'], name='tracking_li_custom__adf488_idx'),
        ),
        migrations.RunPython(backfill_custom_order, migrations.RunPython.noop),
    ]
