# Generated by Django 6.1 on 2026-09-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0022_alter_listitem_options_listitem_custom_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatransferjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('awaiting_confirmation', 'Awaiting confirmation'), ('done', 'Done'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=32),
        ),
    ]
