# Generated by Django 6.1.1 on 2026-10-05 13:21

import tracking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0028_alter_datatransferjob_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatransferjob',
            name='input_file',
            field=models.FileField(blank=True, null=True, upload_to=tracking.models.import_upload_path),
        ),
        migrations.AlterField(
            model_name='datatransferjob',
            name='output_file',
            field=models.FileField(blank=True, null=True, upload_to=tracking.models.export_upload_path),
        ),
    ]
