# Generated by Django 6.1.1 on 2026-10-07 08:10

import django.db.models.functions.comparison
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0030_unique_episode_watch_entries'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='watchentry',
            name='tracking_wa_user_id_9a40c1_idx',
        ),
        migrations.AddIndex(
            model_name='watchentry',
            index=models.Index(fields=['user', 'watched_at'], name='watchentry_user_watched_idx'),
        ),
        migrations.AddIndex(
            model_name='watchentry',
            index=models.Index(models.F('user'), models.OrderBy(django.db.models.functions.comparison.Coalesce('watched_at', 'created_at'), descending=True, nulls_last=True), models.OrderBy(models.F('id'), descending=True), name='watchentry_user_history_idx'),
        ),
    ]
