# Generated by Django 6.1.1 on 2026-10-07 12:14

from datetime import UTC, datetime

from django.conf import settings
from django.db import migrations, models
from django.db.models import F

EPOCH = datetime(1970, 1, 1, tzinfo=UTC)


def unknown_dates_to_null(apps, schema_editor):
    WatchEntry = apps.get_model('tracking', 'WatchEntry')
    UserMediaStatus = apps.get_model('tracking', 'UserMediaStatus')
    # Null used to mean "watched when recorded"; keep that meaning before null starts meaning unknown.
    WatchEntry.objects.filter(watched_at__isnull=True).update(watched_at=F('created_at'))
    # The epoch was the unknown-date marker.
    WatchEntry.objects.filter(watched_at=EPOCH).update(watched_at=None)
    # Dates derived from watches follow their watch: unknown.
    for field in ('started_at', 'completed_at', 'last_watched_at'):
        UserMediaStatus.objects.filter(**{field: EPOCH}).update(**{field: None})
    # Imported status dates without a source date now use the import time; the row creation is the closest record.
    for field in ('dropped_at', 'plan_to_watch_at', 'status_changed_at'):
        UserMediaStatus.objects.filter(**{field: EPOCH}).update(**{field: F('created_at')})



class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0031_watch_entry_history_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(unknown_dates_to_null, migrations.RunPython.noop),
        migrations.RemoveIndex(
            model_name='watchentry',
            name='watchentry_user_history_idx',
        ),
        migrations.AddIndex(
            model_name='watchentry',
            index=models.Index(models.F('user'), models.OrderBy(models.F('watched_at'), descending=True, nulls_last=True), models.OrderBy(models.F('id'), descending=True), name='watchentry_user_history_idx'),
        ),
    ]
